- id: add-pre-commit-hook
  name: add-pre-commit-hook
  entry: add-pre-commit-hook
  description: Add a pre-commit hook to your configuration file if is not already defined
  language: python
  additional_dependencies:
    - pyyaml
  always_run: true
  pass_filenames: false
- id: cloudflare-gh-pages-dns
  name: cloudflare-gh-pages-dns
  entry: cloudflare-gh-pages-dns
  description: Check that the DNS records of a domain managed by Cloudflare are properly configured to serve a Github Pages site
  language: python
  additional_dependencies:
    - cloudflare==2.8.15
  always_run: true
  pass_filenames: false
- id: cloudflare-nameservers
  name: cloudflare-nameservers
  entry: nameservers-endswith-hook -nameserver=cloudflare.com
  description: Check that Cloudflare mannages a domain
  language: python
  pass_filenames: false
  always_run: true
  additional_dependencies:
    - dnspython
- id: dev-extras-required
  name: dev-extras-required
  entry: dev-extras-required-hook
  description: Check if your development dependencies contains all other extras requirements
  files: '(setup\.cfg)|(pyproject\.toml)'
  language: python
- id: nameservers-endswith
  name: nameservers-endswith
  entry: nameservers-endswith-hook
  description: Check if the nameservers of a domain ends with a predefined string
  language: python
  pass_filenames: false
  always_run: true
- id: root-editorconfig-required
  name: root-editorconfig-required
  entry: root-editorconfig-required-hook
  description: Check if your repository has an '.editorconfig' file and if this has a 'root' directive defined as 'true' before section headers
  language: python
  always_run: true
  pass_filenames: false
- id: wavelint
  name: wavelint
  entry: wavelint-hook
  description: Lints WAVE files
  files: \.wav$
  language: python